//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace uwpPlatenInformationScreen.Novasoftware {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.novasoftware.se/webservices", ConfigurationName="Novasoftware.ScheduleFileWebServiceSoap")]
    public interface ScheduleFileWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetErrorAsData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ErrorData> GetErrorAsDataAsync(string description, string culture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetErrorAsString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetErrorAsStringAsync(int pNo, string description, string culture);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetScheduleFileAsXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.GetScheduleFileAsXmlResponse> GetScheduleFileAsXmlAsync(uwpPlatenInformationScreen.Novasoftware.GetScheduleFileAsXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/ReportUserListChange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task ReportUserListChangeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/IsAsleep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> IsAsleepAsync(string schoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.WebServiceStatistics> GetStatisticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/CurrentlyLoading", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CurrentlyLoadingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/BackupFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task BackupFilesAsync(string cookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/Mirror", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> MirrorAsync(string cookie, string URL, string userName, string password, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/SaveFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SaveFilesAsync(string cookie, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetTeachersForGroupOrClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetTeachersForGroupOrClassAsync(string schoolID, string groupOrClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetScheduleIDList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ScheduleID[]> GetScheduleIDListAsync(string schoolID, int lngTypeMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/CreateScheduleSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CreateScheduleSessionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/SetScheduleData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetScheduleDataAsync(string scheduleSessionId, uwpPlatenInformationScreen.Novasoftware.LessonEventInfo[] lessonEvents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetScheduleData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.GetScheduleDataResponse> GetScheduleDataAsync(uwpPlatenInformationScreen.Novasoftware.GetScheduleDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetWeekIDList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.WeekID[]> GetWeekIDListAsync(string schoolID, string period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetScheduleInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ScheduleInfo> GetScheduleInfoAsync(string schoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/SetScheduleInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetScheduleInfoAsync(string cookie, string schoolID, uwpPlatenInformationScreen.Novasoftware.ScheduleInfo sInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/RemoteCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> RemoteCommandAsync(string cookie, int cmdNo, bool recursive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetTextForGUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetTextForGUIDAsync(string schoolID, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task LogoutAsync(string cookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/MethodXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> MethodXmlAsync(string schoolID, string verb, string version, string inData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetIDInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetIDInfoAsync(string schoolID, string IDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetSchoolDataList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolData[]> GetSchoolDataListAsync(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetSchoolStatisticsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolStatistics[]> GetSchoolStatisticsListAsync(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/AssertCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> AssertCodeAsync(string schoolID, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetSchoolStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolStatistics> GetSchoolStatisticsAsync(string schoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetScheduleViewingSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ScheduleViewingPageSettings> GetScheduleViewingSettingsAsync(string schoolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/SetScheduleViewingSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetScheduleViewingSettingsAsync(string cookie, string schoolID, uwpPlatenInformationScreen.Novasoftware.ScheduleViewingPageSettings viewingSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GenerateSchoolId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GenerateSchoolIdAsync(string cookie, string licenseNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetSchoolData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolData> GetSchoolDataAsync(string cookie, string schoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetURLAsync(string cookie, string schoolID, string typeOfURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetGroupContents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetGroupContentsAsync(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/DeleteUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task DeleteUserAsync(string cookie, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/AddUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task AddUserAsync(string cookie, string name, string password, string permission, int level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetLoggedInUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.User> GetLoggedInUserAsync(string cookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetUserDataByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.User> GetUserDataByNameAsync(string cookie, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.User[]> GetUserDataAsync(string cookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/ReloadSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ReloadSettingsAsync(string cookie, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/ReloadFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ReloadFilesAsync(string cookie, string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/EditUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task EditUserAsync(string cookie, int editFlags, string name, string newName, string password, string permission, int level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/d", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> dAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/RemoveScheduleFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task RemoveScheduleFileAsync(string cookie, string schoolID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/RetrieveScheduleFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileResponse> RetrieveScheduleFileAsync(uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/PublishScheduleFile_End", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task PublishScheduleFile_EndAsync(string cookie, bool cancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/GetSoapExceptionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task GetSoapExceptionInfoAsync(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/PublishScheduleFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileResponse> PublishScheduleFileAsync(uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/PublishScheduleFile_Start", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task PublishScheduleFile_StartAsync(string cookie, string dateModified, string loginName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.novasoftware.se/webservices/PublishScheduleFile_CopyBytes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesResponse> PublishScheduleFile_CopyBytesAsync(uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class ErrorData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private int internalCodeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int InternalCode {
            get {
                return this.internalCodeField;
            }
            set {
                this.internalCodeField = value;
                this.RaisePropertyChanged("InternalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string passwordField;
        
        private string addedByField;
        
        private string permissionField;
        
        private int levelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AddedBy {
            get {
                return this.addedByField;
            }
            set {
                this.addedByField = value;
                this.RaisePropertyChanged("AddedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("Permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class ScheduleViewingPageSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool shutDownField;
        
        private string passwordField;
        
        private string cultureField;
        
        private string titleField;
        
        private string logoUrlField;
        
        private string homepageUrlField;
        
        private ScheduleViewingMode modeField;
        
        private int printQualityField;
        
        private bool freeTextField;
        
        private bool rememberPasswordsField;
        
        private int printModeField;
        
        private string backColorField;
        
        private string foreColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ShutDown {
            get {
                return this.shutDownField;
            }
            set {
                this.shutDownField = value;
                this.RaisePropertyChanged("ShutDown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LogoUrl {
            get {
                return this.logoUrlField;
            }
            set {
                this.logoUrlField = value;
                this.RaisePropertyChanged("LogoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HomepageUrl {
            get {
                return this.homepageUrlField;
            }
            set {
                this.homepageUrlField = value;
                this.RaisePropertyChanged("HomepageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ScheduleViewingMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int PrintQuality {
            get {
                return this.printQualityField;
            }
            set {
                this.printQualityField = value;
                this.RaisePropertyChanged("PrintQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool FreeText {
            get {
                return this.freeTextField;
            }
            set {
                this.freeTextField = value;
                this.RaisePropertyChanged("FreeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool RememberPasswords {
            get {
                return this.rememberPasswordsField;
            }
            set {
                this.rememberPasswordsField = value;
                this.RaisePropertyChanged("RememberPasswords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int PrintMode {
            get {
                return this.printModeField;
            }
            set {
                this.printModeField = value;
                this.RaisePropertyChanged("PrintMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BackColor {
            get {
                return this.backColorField;
            }
            set {
                this.backColorField = value;
                this.RaisePropertyChanged("BackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ForeColor {
            get {
                return this.foreColorField;
            }
            set {
                this.foreColorField = value;
                this.RaisePropertyChanged("ForeColor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public enum ScheduleViewingMode {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Split,
        
        /// <remarks/>
        Date,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class SchoolStatistics : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverNameField;
        
        private long peakMemoryUsageField;
        
        private long memoryUsageField;
        
        private long cPUTimeField;
        
        private string schoolIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
                this.RaisePropertyChanged("ServerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long PeakMemoryUsage {
            get {
                return this.peakMemoryUsageField;
            }
            set {
                this.peakMemoryUsageField = value;
                this.RaisePropertyChanged("PeakMemoryUsage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long MemoryUsage {
            get {
                return this.memoryUsageField;
            }
            set {
                this.memoryUsageField = value;
                this.RaisePropertyChanged("MemoryUsage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long CPUTime {
            get {
                return this.cPUTimeField;
            }
            set {
                this.cPUTimeField = value;
                this.RaisePropertyChanged("CPUTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SchoolID {
            get {
                return this.schoolIDField;
            }
            set {
                this.schoolIDField = value;
                this.RaisePropertyChanged("SchoolID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class SchoolData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string cultureField;
        
        private System.DateTime datePublishedField;
        
        private System.DateTime dateOpenedField;
        
        private System.DateTime dateModifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DatePublished {
            get {
                return this.datePublishedField;
            }
            set {
                this.datePublishedField = value;
                this.RaisePropertyChanged("DatePublished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateOpened {
            get {
                return this.dateOpenedField;
            }
            set {
                this.dateOpenedField = value;
                this.RaisePropertyChanged("DateOpened");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
                this.RaisePropertyChanged("DateModified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class ScheduleInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startSchoolYearField;
        
        private System.DateTime endSchoolYearField;
        
        private string cultureField;
        
        private int visibleTypesField;
        
        private int hiddenTypesField;
        
        private string currentWeekField;
        
        private string currentPeriodField;
        
        private bool yearAllowedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime StartSchoolYear {
            get {
                return this.startSchoolYearField;
            }
            set {
                this.startSchoolYearField = value;
                this.RaisePropertyChanged("StartSchoolYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EndSchoolYear {
            get {
                return this.endSchoolYearField;
            }
            set {
                this.endSchoolYearField = value;
                this.RaisePropertyChanged("EndSchoolYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int VisibleTypes {
            get {
                return this.visibleTypesField;
            }
            set {
                this.visibleTypesField = value;
                this.RaisePropertyChanged("VisibleTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int HiddenTypes {
            get {
                return this.hiddenTypesField;
            }
            set {
                this.hiddenTypesField = value;
                this.RaisePropertyChanged("HiddenTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CurrentWeek {
            get {
                return this.currentWeekField;
            }
            set {
                this.currentWeekField = value;
                this.RaisePropertyChanged("CurrentWeek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CurrentPeriod {
            get {
                return this.currentPeriodField;
            }
            set {
                this.currentPeriodField = value;
                this.RaisePropertyChanged("CurrentPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool YearAllowed {
            get {
                return this.yearAllowedField;
            }
            set {
                this.yearAllowedField = value;
                this.RaisePropertyChanged("YearAllowed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class WeekID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class ScheduleData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private int timeField;
        
        private byte[] imageFileDataField;
        
        private string metaFileInfoField;
        
        private string webViewerURLField;
        
        private string noSizeWebViewerURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] ImageFileData {
            get {
                return this.imageFileDataField;
            }
            set {
                this.imageFileDataField = value;
                this.RaisePropertyChanged("ImageFileData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MetaFileInfo {
            get {
                return this.metaFileInfoField;
            }
            set {
                this.metaFileInfoField = value;
                this.RaisePropertyChanged("MetaFileInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string WebViewerURL {
            get {
                return this.webViewerURLField;
            }
            set {
                this.webViewerURLField = value;
                this.RaisePropertyChanged("WebViewerURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NoSizeWebViewerURL {
            get {
                return this.noSizeWebViewerURLField;
            }
            set {
                this.noSizeWebViewerURLField = value;
                this.RaisePropertyChanged("NoSizeWebViewerURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class LessonEventInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startField;
        
        private int lengthField;
        
        private string teacherField;
        
        private string roomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Teacher {
            get {
                return this.teacherField;
            }
            set {
                this.teacherField = value;
                this.RaisePropertyChanged("Teacher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
                this.RaisePropertyChanged("Room");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class ScheduleID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string gUIDField;
        
        private string textField;
        
        private int typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public partial class WebServiceStatistics : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalRequestsField;
        
        private int requestsThisMinuteField;
        
        private int requestsMinuteMaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalRequests {
            get {
                return this.totalRequestsField;
            }
            set {
                this.totalRequestsField = value;
                this.RaisePropertyChanged("TotalRequests");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RequestsThisMinute {
            get {
                return this.requestsThisMinuteField;
            }
            set {
                this.requestsThisMinuteField = value;
                this.RaisePropertyChanged("RequestsThisMinute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RequestsMinuteMax {
            get {
                return this.requestsMinuteMaxField;
            }
            set {
                this.requestsMinuteMaxField = value;
                this.RaisePropertyChanged("RequestsMinuteMax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleFileAsXml", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class GetScheduleFileAsXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] scheduleData;
        
        public GetScheduleFileAsXmlRequest() {
        }
        
        public GetScheduleFileAsXmlRequest(string loginName, string password, byte[] scheduleData) {
            this.loginName = loginName;
            this.password = password;
            this.scheduleData = scheduleData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleFileAsXmlResponse", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class GetScheduleFileAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetScheduleFileAsXmlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=1)]
        public string schoolId;
        
        public GetScheduleFileAsXmlResponse() {
        }
        
        public GetScheduleFileAsXmlResponse(byte[] GetScheduleFileAsXmlResult, string schoolId) {
            this.GetScheduleFileAsXmlResult = GetScheduleFileAsXmlResult;
            this.schoolId = schoolId;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.novasoftware.se/webservices")]
    public enum ScheduleImageFileFormat {
        
        /// <remarks/>
        Wmf,
        
        /// <remarks/>
        Png,
        
        /// <remarks/>
        Gif,
        
        /// <remarks/>
        Bmp,
        
        /// <remarks/>
        Pdf,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleData", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class GetScheduleDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        public bool secureConnection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=1)]
        public uwpPlatenInformationScreen.Novasoftware.ScheduleImageFileFormat fileFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=2)]
        public string schoolID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=3)]
        public int flags;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=4)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=5)]
        public string ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=6)]
        public string period;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=7)]
        public string week;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=8)]
        public int day;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=9)]
        public int mode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=10)]
        public int width;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=11)]
        public int height;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=12)]
        public int maxWidth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=13)]
        public int maxHeight;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=14)]
        public bool printer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=15)]
        public int colors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=16)]
        public bool head;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=17)]
        public bool clock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=18)]
        public bool foot;
        
        public GetScheduleDataRequest() {
        }
        
        public GetScheduleDataRequest(
                    bool secureConnection, 
                    uwpPlatenInformationScreen.Novasoftware.ScheduleImageFileFormat fileFormat, 
                    string schoolID, 
                    int flags, 
                    int type, 
                    string ID, 
                    string period, 
                    string week, 
                    int day, 
                    int mode, 
                    int width, 
                    int height, 
                    int maxWidth, 
                    int maxHeight, 
                    bool printer, 
                    int colors, 
                    bool head, 
                    bool clock, 
                    bool foot) {
            this.secureConnection = secureConnection;
            this.fileFormat = fileFormat;
            this.schoolID = schoolID;
            this.flags = flags;
            this.type = type;
            this.ID = ID;
            this.period = period;
            this.week = week;
            this.day = day;
            this.mode = mode;
            this.width = width;
            this.height = height;
            this.maxWidth = maxWidth;
            this.maxHeight = maxHeight;
            this.printer = printer;
            this.colors = colors;
            this.head = head;
            this.clock = clock;
            this.foot = foot;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleDataResponse", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class GetScheduleDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public uwpPlatenInformationScreen.Novasoftware.ScheduleData ScheduleData;
        
        public GetScheduleDataResponse() {
        }
        
        public GetScheduleDataResponse(uwpPlatenInformationScreen.Novasoftware.ScheduleData ScheduleData) {
            this.ScheduleData = ScheduleData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveScheduleFile", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class RetrieveScheduleFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        public string cookie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=1)]
        public string schoolID;
        
        public RetrieveScheduleFileRequest() {
        }
        
        public RetrieveScheduleFileRequest(string cookie, string schoolID) {
            this.cookie = cookie;
            this.schoolID = schoolID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveScheduleFileResponse", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class RetrieveScheduleFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RetrieveScheduleFileResult;
        
        public RetrieveScheduleFileResponse() {
        }
        
        public RetrieveScheduleFileResponse(byte[] RetrieveScheduleFileResult) {
            this.RetrieveScheduleFileResult = RetrieveScheduleFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishScheduleFile", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class PublishScheduleFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        public string cookie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=1)]
        public string dat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=2)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] barr;
        
        public PublishScheduleFileRequest() {
        }
        
        public PublishScheduleFileRequest(string cookie, string dat, string loginName, string password, byte[] barr) {
            this.cookie = cookie;
            this.dat = dat;
            this.loginName = loginName;
            this.password = password;
            this.barr = barr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishScheduleFileResponse", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class PublishScheduleFileResponse {
        
        public PublishScheduleFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishScheduleFile_CopyBytes", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class PublishScheduleFile_CopyBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=0)]
        public string cookie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.novasoftware.se/webservices", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] barr;
        
        public PublishScheduleFile_CopyBytesRequest() {
        }
        
        public PublishScheduleFile_CopyBytesRequest(string cookie, byte[] barr) {
            this.cookie = cookie;
            this.barr = barr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PublishScheduleFile_CopyBytesResponse", WrapperNamespace="http://www.novasoftware.se/webservices", IsWrapped=true)]
    public partial class PublishScheduleFile_CopyBytesResponse {
        
        public PublishScheduleFile_CopyBytesResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScheduleFileWebServiceSoapChannel : uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScheduleFileWebServiceSoapClient : System.ServiceModel.ClientBase<uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap>, uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ScheduleFileWebServiceSoapClient() : 
                base(ScheduleFileWebServiceSoapClient.GetDefaultBinding(), ScheduleFileWebServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ScheduleFileWebServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleFileWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ScheduleFileWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ScheduleFileWebServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleFileWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ScheduleFileWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleFileWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ScheduleFileWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScheduleFileWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ErrorData> GetErrorAsDataAsync(string description, string culture) {
            return base.Channel.GetErrorAsDataAsync(description, culture);
        }
        
        public System.Threading.Tasks.Task<string> GetErrorAsStringAsync(int pNo, string description, string culture) {
            return base.Channel.GetErrorAsStringAsync(pNo, description, culture);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.GetScheduleFileAsXmlResponse> GetScheduleFileAsXmlAsync(uwpPlatenInformationScreen.Novasoftware.GetScheduleFileAsXmlRequest request) {
            return base.Channel.GetScheduleFileAsXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task ReportUserListChangeAsync() {
            return base.Channel.ReportUserListChangeAsync();
        }
        
        public System.Threading.Tasks.Task<bool> IsAsleepAsync(string schoolID) {
            return base.Channel.IsAsleepAsync(schoolID);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.WebServiceStatistics> GetStatisticsAsync() {
            return base.Channel.GetStatisticsAsync();
        }
        
        public System.Threading.Tasks.Task<string> CurrentlyLoadingAsync() {
            return base.Channel.CurrentlyLoadingAsync();
        }
        
        public System.Threading.Tasks.Task BackupFilesAsync(string cookie) {
            return base.Channel.BackupFilesAsync(cookie);
        }
        
        public System.Threading.Tasks.Task<int> MirrorAsync(string cookie, string URL, string userName, string password, string group) {
            return base.Channel.MirrorAsync(cookie, URL, userName, password, group);
        }
        
        public System.Threading.Tasks.Task SaveFilesAsync(string cookie, string group) {
            return base.Channel.SaveFilesAsync(cookie, group);
        }
        
        public System.Threading.Tasks.Task<string> GetTeachersForGroupOrClassAsync(string schoolID, string groupOrClass) {
            return base.Channel.GetTeachersForGroupOrClassAsync(schoolID, groupOrClass);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ScheduleID[]> GetScheduleIDListAsync(string schoolID, int lngTypeMask) {
            return base.Channel.GetScheduleIDListAsync(schoolID, lngTypeMask);
        }
        
        public System.Threading.Tasks.Task<string> CreateScheduleSessionAsync() {
            return base.Channel.CreateScheduleSessionAsync();
        }
        
        public System.Threading.Tasks.Task SetScheduleDataAsync(string scheduleSessionId, uwpPlatenInformationScreen.Novasoftware.LessonEventInfo[] lessonEvents) {
            return base.Channel.SetScheduleDataAsync(scheduleSessionId, lessonEvents);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.GetScheduleDataResponse> uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap.GetScheduleDataAsync(uwpPlatenInformationScreen.Novasoftware.GetScheduleDataRequest request) {
            return base.Channel.GetScheduleDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.GetScheduleDataResponse> GetScheduleDataAsync(
                    bool secureConnection, 
                    uwpPlatenInformationScreen.Novasoftware.ScheduleImageFileFormat fileFormat, 
                    string schoolID, 
                    int flags, 
                    int type, 
                    string ID, 
                    string period, 
                    string week, 
                    int day, 
                    int mode, 
                    int width, 
                    int height, 
                    int maxWidth, 
                    int maxHeight, 
                    bool printer, 
                    int colors, 
                    bool head, 
                    bool clock, 
                    bool foot) {
            uwpPlatenInformationScreen.Novasoftware.GetScheduleDataRequest inValue = new uwpPlatenInformationScreen.Novasoftware.GetScheduleDataRequest();
            inValue.secureConnection = secureConnection;
            inValue.fileFormat = fileFormat;
            inValue.schoolID = schoolID;
            inValue.flags = flags;
            inValue.type = type;
            inValue.ID = ID;
            inValue.period = period;
            inValue.week = week;
            inValue.day = day;
            inValue.mode = mode;
            inValue.width = width;
            inValue.height = height;
            inValue.maxWidth = maxWidth;
            inValue.maxHeight = maxHeight;
            inValue.printer = printer;
            inValue.colors = colors;
            inValue.head = head;
            inValue.clock = clock;
            inValue.foot = foot;
            return ((uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap)(this)).GetScheduleDataAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.WeekID[]> GetWeekIDListAsync(string schoolID, string period) {
            return base.Channel.GetWeekIDListAsync(schoolID, period);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ScheduleInfo> GetScheduleInfoAsync(string schoolID) {
            return base.Channel.GetScheduleInfoAsync(schoolID);
        }
        
        public System.Threading.Tasks.Task SetScheduleInfoAsync(string cookie, string schoolID, uwpPlatenInformationScreen.Novasoftware.ScheduleInfo sInfo) {
            return base.Channel.SetScheduleInfoAsync(cookie, schoolID, sInfo);
        }
        
        public System.Threading.Tasks.Task<int> RemoteCommandAsync(string cookie, int cmdNo, bool recursive) {
            return base.Channel.RemoteCommandAsync(cookie, cmdNo, recursive);
        }
        
        public System.Threading.Tasks.Task<string> GetTextForGUIDAsync(string schoolID, string GUID) {
            return base.Channel.GetTextForGUIDAsync(schoolID, GUID);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string cookie) {
            return base.Channel.LogoutAsync(cookie);
        }
        
        public System.Threading.Tasks.Task<string> MethodXmlAsync(string schoolID, string verb, string version, string inData) {
            return base.Channel.MethodXmlAsync(schoolID, verb, version, inData);
        }
        
        public System.Threading.Tasks.Task<string> GetIDInfoAsync(string schoolID, string IDList) {
            return base.Channel.GetIDInfoAsync(schoolID, IDList);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolData[]> GetSchoolDataListAsync(string group) {
            return base.Channel.GetSchoolDataListAsync(group);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolStatistics[]> GetSchoolStatisticsListAsync(string group) {
            return base.Channel.GetSchoolStatisticsListAsync(group);
        }
        
        public System.Threading.Tasks.Task<bool> AssertCodeAsync(string schoolID, string code) {
            return base.Channel.AssertCodeAsync(schoolID, code);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolStatistics> GetSchoolStatisticsAsync(string schoolID) {
            return base.Channel.GetSchoolStatisticsAsync(schoolID);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.ScheduleViewingPageSettings> GetScheduleViewingSettingsAsync(string schoolId) {
            return base.Channel.GetScheduleViewingSettingsAsync(schoolId);
        }
        
        public System.Threading.Tasks.Task SetScheduleViewingSettingsAsync(string cookie, string schoolID, uwpPlatenInformationScreen.Novasoftware.ScheduleViewingPageSettings viewingSettings) {
            return base.Channel.SetScheduleViewingSettingsAsync(cookie, schoolID, viewingSettings);
        }
        
        public System.Threading.Tasks.Task<string> GenerateSchoolIdAsync(string cookie, string licenseNumber) {
            return base.Channel.GenerateSchoolIdAsync(cookie, licenseNumber);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.SchoolData> GetSchoolDataAsync(string cookie, string schoolID) {
            return base.Channel.GetSchoolDataAsync(cookie, schoolID);
        }
        
        public System.Threading.Tasks.Task<string> GetURLAsync(string cookie, string schoolID, string typeOfURL) {
            return base.Channel.GetURLAsync(cookie, schoolID, typeOfURL);
        }
        
        public System.Threading.Tasks.Task<string> GetGroupContentsAsync(string group) {
            return base.Channel.GetGroupContentsAsync(group);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(string cookie, string name) {
            return base.Channel.DeleteUserAsync(cookie, name);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(string cookie, string name, string password, string permission, int level) {
            return base.Channel.AddUserAsync(cookie, name, password, permission, level);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.User> GetLoggedInUserAsync(string cookie) {
            return base.Channel.GetLoggedInUserAsync(cookie);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.User> GetUserDataByNameAsync(string cookie, string userName) {
            return base.Channel.GetUserDataByNameAsync(cookie, userName);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.User[]> GetUserDataAsync(string cookie) {
            return base.Channel.GetUserDataAsync(cookie);
        }
        
        public System.Threading.Tasks.Task<int> ReloadSettingsAsync(string cookie, string group) {
            return base.Channel.ReloadSettingsAsync(cookie, group);
        }
        
        public System.Threading.Tasks.Task<int> ReloadFilesAsync(string cookie, string group) {
            return base.Channel.ReloadFilesAsync(cookie, group);
        }
        
        public System.Threading.Tasks.Task EditUserAsync(string cookie, int editFlags, string name, string newName, string password, string permission, int level) {
            return base.Channel.EditUserAsync(cookie, editFlags, name, newName, password, permission, level);
        }
        
        public System.Threading.Tasks.Task<int> dAsync() {
            return base.Channel.dAsync();
        }
        
        public System.Threading.Tasks.Task RemoveScheduleFileAsync(string cookie, string schoolID) {
            return base.Channel.RemoveScheduleFileAsync(cookie, schoolID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileResponse> uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap.RetrieveScheduleFileAsync(uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileRequest request) {
            return base.Channel.RetrieveScheduleFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileResponse> RetrieveScheduleFileAsync(string cookie, string schoolID) {
            uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileRequest inValue = new uwpPlatenInformationScreen.Novasoftware.RetrieveScheduleFileRequest();
            inValue.cookie = cookie;
            inValue.schoolID = schoolID;
            return ((uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap)(this)).RetrieveScheduleFileAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PublishScheduleFile_EndAsync(string cookie, bool cancel) {
            return base.Channel.PublishScheduleFile_EndAsync(cookie, cancel);
        }
        
        public System.Threading.Tasks.Task GetSoapExceptionInfoAsync(string description) {
            return base.Channel.GetSoapExceptionInfoAsync(description);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileResponse> uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap.PublishScheduleFileAsync(uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileRequest request) {
            return base.Channel.PublishScheduleFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileResponse> PublishScheduleFileAsync(string cookie, string dat, string loginName, string password, byte[] barr) {
            uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileRequest inValue = new uwpPlatenInformationScreen.Novasoftware.PublishScheduleFileRequest();
            inValue.cookie = cookie;
            inValue.dat = dat;
            inValue.loginName = loginName;
            inValue.password = password;
            inValue.barr = barr;
            return ((uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap)(this)).PublishScheduleFileAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PublishScheduleFile_StartAsync(string cookie, string dateModified, string loginName, string password) {
            return base.Channel.PublishScheduleFile_StartAsync(cookie, dateModified, loginName, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesResponse> uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap.PublishScheduleFile_CopyBytesAsync(uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesRequest request) {
            return base.Channel.PublishScheduleFile_CopyBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesResponse> PublishScheduleFile_CopyBytesAsync(string cookie, byte[] barr) {
            uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesRequest inValue = new uwpPlatenInformationScreen.Novasoftware.PublishScheduleFile_CopyBytesRequest();
            inValue.cookie = cookie;
            inValue.barr = barr;
            return ((uwpPlatenInformationScreen.Novasoftware.ScheduleFileWebServiceSoap)(this)).PublishScheduleFile_CopyBytesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ScheduleFileWebServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ScheduleFileWebServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://www.novasoftware.se/schedulewebservice/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ScheduleFileWebServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.ScheduleFileWebServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ScheduleFileWebServiceSoapClient.GetEndpointAddress(EndpointConfiguration.ScheduleFileWebServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            ScheduleFileWebServiceSoap,
        }
    }
}
